# General Information
name: The Croft House, Borve, Isle of Harris
short_name: The Croft House
description: The Croft House is a comfortable modernised island holiday cottage. Nestled amongst some of the most spectacular scenery in Scotland, and with beaches to rival anywhere in the world, come and relax in comfort and enjoy the best of the Outer Hebrides..
email:
website: http://borvecrofthouse.co.uk
form: 21a09d10d78ca264d1e2b3aa1f8f8270
primary_colour: blue
secondary_colour: white
